version: "3"

services:
  dnsmasq:
    build: ./dnsmasq
    volumes:
      - ./data/pxe-config/dnsmasq.conf:/etc/dnsmasq.conf
      - ./data/tftp/:/tftp/
    network_mode: host
    
  http:
    build: ./http
    network_mode: host
    volumes:
      - ./data/os:/usr/share/nginx/html/os
      - ./data/init-config/:/usr/share/nginx/html/init-config
    environment:
      NGINX_PORT: 80
